#!/bin/sh
#
# @name Generic Quadplane VTOL
#
# @type Reaper VTOL
# @class VTOL
#
# @maintainer
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
# Maybe this will work (DOUBT)
	param set MC_ROLL_P 7
	param set MC_ROLLRATE_P 0.15
	param set MC_ROLLRATE_I 0.002
	param set MC_ROLLRATE_D 0.003
	param set MC_ROLLRATE_FF 0
	param set MC_PITCH_P 7
	param set MC_PITCHRATE_P 0.12
	param set MC_PITCHRATE_I 0.002
	param set MC_PITCHRATE_D 0.003
	param set MC_PITCHRATE_FF 0
	param set MC_YAW_P 2.8
	param set MC_YAWRATE_P 0.22
	param set MC_YAWRATE_I 0.02
	param set MC_YAWRATE_D 0
	param set MC_YAWRATE_FF 0
	param set MC_YAWRATE_MAX 40
	param set MC_YAWRAUTO_MAX 40

	param set PWM_AUX_DIS5 950
	param set PWM_RATE 400

	param set VT_TYPE 2
	param set VT_MOT_COUNT 4
	param set VT_F_TRANS_THR 0.75
	param set VT_IDLE_PWM_MC 1080 #IDLE Speed in MULTCOPT mode
	param set RC_MAP_TRANS_SW 5
fi

set MAV_TYPE 22

set MIXER quad_+
set MIXER_AUX vtol_AAVVT

set PWM_OUT 1234
